### ISSUE TITLE
Installing MySQL in Asterisk and Saving the dialed DTMF to mysql database

### ISSUE THREAD

**Issue by Jabiulla24** [janastu/regiN#10]
Need to save the user dialed DTMF Options with caller ID in  MySQL database

**Comment by Jabiulla24** [comment]
By default the asterisk is saving the call recordings to the cdr table in asteriskcdrdb

**Comment by salus-sage** [comment]
What does that mean?

**Comment by Madhuvanthi-A** [comment]
Saving DTMF in MySQL databse via Asterisk dialplan.
