### ISSUE TITLE
Uploading the audio files in different path and playing in IVR Menu

### ISSUE THREAD

**Issue by Jabiulla24** [janastu/regiN#12]
By default the asterisk sound files are stored in /var/lib/asterisk/sounds/en need to change the path and play the audio files from that path in ivr menu

**Comment by Jabiulla24** [comment]
I have chosen the path as /usr/local/asterisk/sounds/ivr and copied the audio files to this path and access the audio files

Set the global variable path of audio to /usr/local/asterisk/sounds/ivr and use the global variable everywhere needed

Set(GLOBAL(PATH)='usr/local/asterisk/sounds/ivr')
and use backgorund(${PATH}/welcome_message)

**Comment by salus-sage** [comment]
I don't see how a path settings can affect. If we know where to put our
audio, the that's it, u create another for fr for French and so on.
