### ISSUE TITLE
Setup call routing in 2N voice blue next

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/regiN#4]

**Comment by Jabiulla24** [comment]
Able to receive the call and forward on entering the extension to 100 and able to hear the pre recorded voice

**Comment by Jabiulla24** [comment]
Call Routing 

Calling to the particular GSM number the asterisk need to receive the call and after entering the extension it should route to the extension

It is achieved by setting VOIP parmaters in 2N Voice blue next web interface ,creating the sip account in sip.conf file and declaring extensions in extensions.conf file
