### ISSUE TITLE
Auto dialing extension after connecting to asterisk

### ISSUE THREAD

**Issue by Jabiulla24** [janastu/regiN#7]
After calls get connect the asterisk server ,the extension should be auto dial an on receiving extension the extension should be called

**Comment by Jabiulla24** [comment]
In Web Interface of Voice Blue Next it has the option in GSM incoming groups as List of Called Numbers and if we add the numbers (say 100) and in extensions.conf we have extensions then the call is transferred to the particular extensions else it is not getting transferred.

So we need to dial extension after call gets connected

**Comment by Jabiulla24** [comment]
Need to enable the option  for  Skip DTMF for numbers not in CLIP Routing table in GSM incoming groups of 2n web interface

**Comment by salus-sage** [comment]
Anything related to hardware voice blue next can't be relied upon anymore.
