### ISSUE TITLE
Install Asterisk in Docker for testing in Server

### ISSUE THREAD

**Issue by Jabiulla24** [janastu/regiN#9]
As asterisk is installed in Virtual Machine and tested the ivr menu ,need to test in Server by installing it in docker

**Comment by Jabiulla24** [comment]
Duplicate of issue no #11

**Comment by salus-sage** [comment]
We Shud keep this at low priority, as the requirements doesn't specify, and
if we are able to ship a VM, to be installed on site, that Shud work.
